selenium-hub:
  image: selenium/hub
  ports:
    - "8888:4444"

chrome:
    image: selenium/node-chrome
    links:
      - selenium-hub:hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

firefox:
    image: selenium/node-firefox
    links:
      - selenium-hub:hub
